### ISSUE TITLE
Paying tribute to our CI tools

### ISSUE THREAD

**Issue by BraedonWooding** [OrderOfThePorcupine/ProjectPorcupine#252]
Just had an idea and felt it was worth documenting before I forgot.  It would be quite nice I think to pay tribute to our tools in some way.

- Maybe there is a random event where a 'stylecop' comes and sees if your crew are wearing fashionable outfits and if your base is clean else you get a fine!
- Travis and Stylecop are both names that our little astronauts can have, where Travis is spawned and doesn't have a head (i.e. headless haha) and stylecop maybe has a badge and favourite food is donuts or something.
- Maybe some event for travis where he checks to see if anything in your base is broken else you get a fine!

**Comment by RyTechro** [comment]
I like the idea but it should not be a gameplay mechanic in my opinion. If you lose money (get a fine) because we implemented a joke/tribute I think it will hurt the game

**Comment by BraedonWooding** [comment]
If it is a small amount I don't think it'll matter but yes that is a fair point

**Comment by kd7uiy** [comment]
Have a random event where the Style Cop visits, and anyone who is nearby has a stylish outfit, that they discard as soon as the cop's back is away from them?

**Comment by koosemose** [comment]
Maybe I'm a killjoy, but I don't even like having contributors names for characters. It's fine while we're in the "there's still not much of a game here" stage of development, but at some point I'd like to have names that sound like actual people's names (which, let's be honest, most of ours don't), at most having contrib names as occasional nicknames (and even then with some names it reads awkward)

**Comment by BraedonWooding** [comment]
See I agree with you (that is why I suggested some sort of event rather than just as characters).

I would rather have it so that contributors are NPC's (that is out of the player's control) or something similar; people who submit art / music become X chaerract, people who contribute to code become Y character and so on.

That is we still pay tribute but don't have to pay the cost of having a user get a character with a weird name whose name acts as a barrier to them getting into the game (since they may not be able to comfortably pronounce/say it)

**Comment by kd7uiy** [comment]
Let's just do the tribute to the tools the easy way, make a headline or two about it. If we want to do something more complex later on, we can do that.
